# -*- coding: utf-8 -*-
"""ML model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TWTIWkfPPn4qbr72hCnstnsRLHADttGZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df = pd.read_excel('/content/barley (2).xlsx')
display(df.head())

# Optional: install category_encoders if not already available in Colab
!pip install category-encoders
from category_encoders import TargetEncoder

# 2. Clean Target Variables & Numeric Inputs at the top
df["GY"] = pd.to_numeric(df["GY"], errors="coerce")
df["BY"] = pd.to_numeric(df["BY"], errors="coerce")
df["Rate"] = pd.to_numeric(df["Rate"], errors="coerce")

# Drop rows where target conversion failed
df = df.dropna(subset=["GY"]).reset_index(drop=True)

print("Data loaded and cleaned successfully. Data shape:", df.shape)

df.info()

# Check for missing values
missing_values = df.isnull().sum()
display(missing_values[missing_values > 0].sort_values(ascending=False))

df.duplicated().sum()

# --- Convert string column(s) to float ---

df["GY"] = pd.to_numeric(df["GY"], errors="coerce")
df["BY"] = pd.to_numeric(df["BY"], errors="coerce")

# Optional: drop rows where conversion failed (now NaN)
df = df.dropna(subset=["GY", "BY"]).reset_index(drop=True)

print(df[["GY", "BY"]].dtypes)

#1. Boxplot of GY across Nutrient types - see which nutrient gives higher yield
plt.figure(figsize=(8, 5))
sns.boxplot(x='Nutrient', y='GY', data=df)
plt.title('Grain Yield (GY) by Nutrient Type')
plt.show()

# 2. Histograms - distribution shape of each numeric variable
plt.figure(figsize=(15, 4))
numerical_cols = ['Rep', 'Rate', 'GY', 'BY']
for i, col in enumerate(numerical_cols):
    plt.subplot(1, 4, i + 1)
    sns.histplot(df[col], kde=True, bins=30)
    plt.title(f'Distribution of {col}')
plt.tight_layout()
plt.show()

# 3. Countplot  → whether your data is balanced across the 13 locations
plt.figure(figsize=(12, 5))
sns.countplot(x='Location', data=df, order=df['Location'].value_counts().index)
plt.xticks(rotation=45)
plt.title('Number of Records per Location')
plt.tight_layout()
plt.show()

# 4. Scatter plot → whether higher nutrient rate is associated with higher yield
plt.figure(figsize=(7, 5))
sns.scatterplot(x='Rate', y='GY', hue='Nutrient', data=df)
plt.title('GY vs Rate, colored by Nutrient')
plt.show()

# 6. Correlation heatmap → strength of linear relationship between GY, BY, and Rate
numerical_cols = ['Rep', 'Rate', 'GY', 'BY']
plt.figure(figsize=(5, 4))
sns.heatmap(df[numerical_cols].corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

# 1. Define Target & Features
TARGET = "GY"
target_encoded_features = ["Location", "SOIL_TYPE", "Agro_Ecological_Zone"]
ohe_features = ["Nutrient"]
numeric_features = ["Rate"]

X = df[target_encoded_features + ohe_features + numeric_features]
y = df[TARGET]

# Train / Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 2. Advanced Preprocessor: Target Encoding + One-Hot Encoding
preprocessor = ColumnTransformer(
    transformers=[
        ("target_enc", TargetEncoder(), target_encoded_features),
        ("ohe", OneHotEncoder(handle_unknown="ignore"), ohe_features),
    ],
    remainder="passthrough",
)

# 3. Model Definitions (Restricted depths to prevent overfitting)
models = {
    "Random Forest": RandomForestRegressor(
        n_estimators=500, max_depth=6, min_samples_leaf=3, random_state=42, n_jobs=-1
    ),
    "Gradient Boosting": GradientBoostingRegressor(
        n_estimators=300, learning_rate=0.03, max_depth=4, subsample=0.8, random_state=42
    ),
}

results = {}

# 4. Train and Evaluate
for name, model in models.items():
    pipe = Pipeline(steps=[("preprocess", preprocessor), ("model", model)])

    # Cross-validation evaluated strictly on training set to avoid leakage
    cv_scores = cross_val_score(pipe, X_train, y_train, cv=5, scoring="r2")

    # Fit model on training set
    pipe.fit(X_train, y_train)
    preds = pipe.predict(X_test)

    mae = mean_absolute_error(y_test, preds)
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    r2 = r2_score(y_test, preds)

    results[name] = {
        "pipeline": pipe,
        "MAE": mae,
        "RMSE": rmse,
        "R2": r2,
        "CV_R2_mean": cv_scores.mean(),
        "CV_R2_std": cv_scores.std(),
    }

    print(f"\n--- {name} ---")
    print(f"Test MAE      : {mae:.2f}")
    print(f"Test RMSE     : {rmse:.2f}")
    print(f"Test R2       : {r2:.3f}")
    print(f"5-Fold CV R2  : {cv_scores.mean():.3f} (+/- {cv_scores.std():.3f})")

# 6. Feature importance (from Random Forest)
# ---------------------------------------------------------------
best_name = max(results, key=lambda k: results[k]["R2"])
best_pipe = results[best_name]["pipeline"]
print(f"\nBest model on test set: {best_name}")

# Get all feature names from the ColumnTransformer in the correct order
# This method accounts for all transformers (target_enc, ohe) and remainder='passthrough'
all_feature_names = best_pipe.named_steps["preprocess"].get_feature_names_out()

model_step = best_pipe.named_steps["model"]
if hasattr(model_step, "feature_importances_"):
    importances = model_step.feature_importances_
    # Ensure the number of importances matches the number of feature names
    if len(importances) == len(all_feature_names):
        imp_df = pd.DataFrame(
            {"feature": all_feature_names, "importance": importances}
        ).sort_values("importance", ascending=False)
        print("\nTop 10 most important features:")
        print(imp_df.head(10).to_string(index=False))
    else:
        print(f"Warning: Mismatch between number of feature importances ({len(importances)}) and feature names ({len(all_feature_names)}).")
        print("Feature importances cannot be accurately mapped to names. Please re-run the pipeline.")

import joblib

# Get the name of the best performing model again
best_name = max(results, key=lambda k: results[k]["R2"])

# Grab your best trained pipeline (which includes preprocessing + model)
best_pipeline = results[best_name]["pipeline"]

# Save it to disk
joblib.dump(best_pipeline, "barley_model_pipeline.pkl")
print("Model saved successfully as barley_model_pipeline.pkl!")

from google.colab import files

files.download("barley_model_pipeline.pkl")
# replace with your actual second filename